# Generated by Django 4.0.1 on 2022-01-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0028_tutorpost_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpost',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
